# Generated by Django 5.0 on 2023-12-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoran',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=155),
        ),
    ]
